config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list, message: "Ce film est déjà ajouté à cette liste"}
end

app/models/list.rb
class List < ApplicationRecord
  # Une liste a plusieurs signets
  has_many :bookmarks, dependent: :destroy
  # Une liste a plusieurs films avec des signets
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    # Un film a plusieurs signets
    has_many :bookmarks
    # Un film doit avoir un titre unique et un aperçu.
    validates :title, presence: true, uniqueness: true
    validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = @list.bookmarks.new
  end

  def create
    @bookmark = @list.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to @list, notice: "Bookmark ajouté!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark.list, notice: "Bookmark supprimé."
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: "liste créée!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to @lists_path, notice: "liste supprimée!"
  end

  private
  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= form_with(model: [@list, @bookmark], local: true) do |form| %>
  <div>
    <%= form.label :movie_id %>
    <%= form.collection_select :movie_id, Movie.all, :id, :title %>
  </div>

  <div>
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <%= form.submit "Add Bookmark" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class=container>
<h1>All Lists</h1>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<%= link_to "Create a movie list", new_list_path %></li>


</div>

app/views/lists/new.html.erb
<h1>Créer une nouvelle liste</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name, label: "Nom de la liste" %>

  <%= f.submit "Créer", class: "btn btn-primary" %>
<% end %>

<%= link_to "Retour aux listes", lists_path, class: "btn btn-secondary" %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<h2>Bookmarks</h2>
<ul>
  <% @bookmarks.each do |bookmark| %>
    <li>
      <%= bookmark.movie.title %><br>
      <strong>Commentaire :</strong> <%= bookmark.comment %><br>
      <strong><%= link_to "Supprimer", list_bookmark_path(@list, bookmark), method: :delete, data: { confirm: "Es-tu sûr ?" } %></strong>
    </li>
  <% end %>
</ul>

<%= link_to "Ajouter un Bookmark", new_list_bookmark_path(@list) %>